title: <font color="#616A6B"> Trevor Kapuvari # your name (or website title) here
logo: "/images/pfpBlurred.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Geospatial Specialist, Data Scientist, Urban Planning Enthusiast
  <br><br>
  <br><br>
  <meta charset="utf-8">
<title>Redirecting to https://example.com/</title>
<meta http-equiv="refresh" content="0; URL=https://drive.google.com/file/d/1n6CQuPejRg5zOLeshYDBtHBQV6vCpeDv/view">
<link rel="canonical" href="https://drive.google.com/file/d/1n6CQuPejRg5zOLeshYDBtHBQV6vCpeDv/view">
  <a href="https://www.linkedin.com/in/trevor-kapuvari/">LinkedIn</a> <br> </br>
  <a href="https://drive.google.com/file/d/173Tj-AjHdkO1jMOKxpACperlWdzmXSES/view?usp=sharing">Resume</a>



  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
markdown: kramdown
